[package]
name = "bulk_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.11"
drift = { git = "https://github.com/drift-labs/protocol-v2.git", rev = "v2.92.0", features = ["cpi", "mainnet-beta"]}

[lib]
name = "bulk_engine"
crate-type = ["cdylib", "lib"]